imports:
    - { resource: doctrine/ }

doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: '%env(resolve:DATABASE_VERSION)%'
        driver: 'pdo_pgsql'
        charset: utf8
    orm:
        connection: default
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
