doctrine_migrations:
    all_or_nothing: true
    migrations_paths:
        'App\Shared\Infrastructure\Persistence\Doctrine\Migration': '%kernel.project_dir%/src/Shared/Infrastructure/Persistence/Doctrine/Migration'
