DROP DATABASE IF EXISTS symfony;
DROP DATABASE IF EXISTS symfony_test;
DROP USER IF EXISTS symfony;

CREATE USER symfony WITH PASSWORD 'symfony';
CREATE DATABASE symfony;
GRANT ALL PRIVILEGES ON DATABASE symfony TO symfony;

CREATE DATABASE symfony_test;
GRANT ALL PRIVILEGES ON DATABASE symfony_test TO symfony;