version: "3.3"
services:
  app:
    image: symfony:local
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      args:
        ADDITIONAL_PACKAGES: "php8.0-xdebug git"
    env_file: .env
    volumes:
      - .:/app:delegated
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "5m"
    networks:
      app_net:
    depends_on:
      - pgsql
      - rmq

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - .:/app
    ports:
      - "80:80"
    networks:
      app_net:
    depends_on:
      - app

  rmq:
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      app_net:
    volumes:
      - rabbit_data:/var/lib/rabbitmq/mnesia

  pgsql:
    image: postgres:${DATABASE_VERSION}
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      app_net:
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      app_net:

networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"

volumes:
  postgres_data:
  rabbit_data:
