shared:
  resource: ../../src/Shared/UI/Controller/
  type: annotation

module_demo:
  resource: ../../src/Demo/UI/Controller/
  type: annotation

kernel:
  resource: ../../src/Kernel.php
  type: annotation
